const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Plugins.Keyboard,
		C3.Behaviors.Follow,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.OnLayoutStart
	];
};
self.C3_JsPropNameTable = [
	{grama: 0},
	{ANIM: 0},
	{DIR: 0},
	{MovimentoEmGrid: 0},
	{jogador: 0},
	{Teclado: 0},
	{vida: 0},
	{Seguir: 0},
	{esqueleto: 0},
	{Sólido: 0},
	{arbusto: 0},
	{PedraBaixo: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{bau: 0},
	{Mouse: 0},
	{titulo: 0},
	{Texto: 0},
	{Texto2: 0},
	{SIM: 0},
	{NAO: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Áudio: 0},
	{Vidas: 0}
];

self.InstanceType = {
	grama: class extends self.ITiledBackgroundInstance {},
	jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	vida: class extends self.ISpriteInstance {},
	esqueleto: class extends self.ISpriteInstance {},
	arbusto: class extends self.ISpriteInstance {},
	PedraBaixo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	titulo: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	SIM: class extends self.ITextInstance {},
	NAO: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {}
}